### ISSUE TITLE
no_log option set to true makes it very hard to find issues

### ISSUE THREAD

**Issue by stevenengland** [paperless-ngx/ansible#14]
Hi there,

when using this role it is kind of hard to troubleshoot misconfigurations when excessive configuration blocks like this one have set their no_log property to true:

```
- name: configure paperless-ngx
  ansible.builtin.lineinfile:
    path: "{{ paperlessng_directory }}/paperless.conf.template"
    regexp: ^#?{{ item.regexp }}=
    line: "{{ item.line }}"
  with_items:
   <alotofitemshere>
```
I know there are good reasons to hide these logs. But I needed to manually turn on logging just to recognize I had a type in a variable.

Non ideal ideas so far:

- Splitting the configuration via lineinfile in smaller chunks
- Make a separete task with no_log: true only for really sensitive options
