### ISSUE TITLE
Problem with checks for installed versions when initial installation failed

### ISSUE THREAD

**Issue by stevenengland** [paperless-ngx/ansible#16]
Hi there, when an initial installation failed somewhere after # 5 there is a chain of problems originating from this code:
```
# 1
- name: check for existing paperless-ngx version file
  ansible.builtin.stat:
    path: "{{ paperlessng_directory }}/.installed_version"
  register: paperlessng_current_commitfile

# 2
- name: get the current installed version as commit
  ansible.builtin.command:
    cmd: cat {{ paperlessng_directory }}/.installed_version
  changed_when: paperlessng_current_commit.stdout != paperlessng_commit | string
  failed_when: false
  ignore_errors: true
  register: paperlessng_current_commit
  when: paperlessng_current_commitfile.stat.exists

# 3
- name: register current state
  ansible.builtin.set_fact:
    fresh_installation: "{{ not paperlessng_current_commitfile.stat.exists }}"
    update_installation: false
    reconfigure_only: false
# 4
- name: register current existing state
  ansible.builtin.set_fact:
    update_installation: "{{ paperlessng_current_commit.stdout != paperlessng_commit | string }}"
    reconfigure_only: "{{ paperlessng_current_commit.stdout == paperlessng_commit | string }}"
  when: not fresh_installation

[...]

# 5
    - name: store commit hash of installed version
      ansible.builtin.copy:
        content: "{{ paperlessng_commit }}"
        dest: "{{ paperlessng_directory }}/.installed_version"
        owner: "{{ paperlessng_system_user }}"
        group: "{{ paperlessng_system_group }}"
        mode: "0440"
```

-# 5 registers a "installed" version very early. I think it should be executed at the end of the playbook. Because otherwise:

-# 1 checks for this "installed" version and then subsequent tasks like # 2, # 3, # 4 will do as if there was a complete installation which leads to wrong assumptions later in the role when checks for fresh_installation etc. are executed.

Like in my case: 
```
TASK [paperless-ngx : configure paperless superuser] ***********************************************************************************************************************************************************************************************************************fatal: [paperless_ngx]: FAILED! => changed=false 
  cmd:
  - /opt/paperless-ngx/.venv/bin/python3
  - /opt/paperless-ngx/src/manage.py
  - manage_superuser
  delta: '0:00:00.040121'
  end: '2022-12-23 09:16:45.750421'
  msg: non-zero return code
  rc: 1
  start: '2022-12-23 09:16:45.710300'
  stderr: |-
    Traceback (most recent call last):
      File "/opt/paperless-ngx/src/manage.py", line 9, in <module>
        from django.core.management import execute_from_command_line
    ModuleNotFoundError: No module named 'django'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

Because tasks before this one were skipped.
