### ISSUE TITLE
Improve documentation for Install/Upgrade path

### ISSUE THREAD

**Issue by SiM22** [paperless-ngx/ansible#5]
Seeing as this might start getting a bit more use, I have noticed there are some vars set within one of the steps that defines what tasks are actioned or not. This is something I will work on, just adding here for tracking/visibility/memory.

```
- name: register current state
  set_fact:
    fresh_installation: '{{ not paperlessng_current_commitfile.stat.exists }}'
    update_installation: false
    reconfigure_only: false
```

As is above it will do a fresh install, but if any of those change then the role will fail as it may or may no have done the prerequisites.

It is 1am so apologies if it does not make sense, will take a look in the morning and see if this issue reads ok. If not I will edit.
