### ISSUE TITLE
Reconfigure paperlessng_listen_address on second playbook run

### ISSUE THREAD

**Issue by Tronde** [paperless-ngx/ansible#9]
Hello Team,  
At first let me thank you for this Ansible role. I was writing one of my own and almost finished when I found this project. It's great. Thank you for it.

I've found an unexpected behaviour though which I would like to address here. I installed paperless-ngx on a host using the following playbook:

```
---
- hosts: paperless-ngx.example.com
  tasks:
    - name: Make sure pip3 is installed
      apt:
       name: python3-pip
       state: latest

    - name: Include role ansible-role-paperless-ngx
      include_role:
        name: ansible-role-paperless-ngx
      vars:
        paperlessng_secret_key: >-
          lookup('community.general.random_string', base64=True, length=64)
        paperlessng_listen_address: 127.0.0.1
```

Paperless is listening on socket 127.0.0.1:8000:

```
# ss -ltn
State          Recv-Q         Send-Q                 Local Address:Port                 Peer Address:Port         Process         
LISTEN         0              2048                       127.0.0.1:8000                      0.0.0.0:*                            
LISTEN         0              511                        127.0.0.1:6379                      0.0.0.0:*                            
LISTEN         0              128                          0.0.0.0:22                        0.0.0.0:*
```

Now I changed the listening address to `paperlessng_listen_address: 0.0.0.0` and ran the playbook again. But the service keeps listening on `127.0.0.1:8000`. I would expect to change the socket with the second run.

My guess is, that the services just needs to be reloaded or rather restarted. Can someone confirm this behaviour and is it possible to fix it?

Best regards,  
Tronde
